### ISSUE TITLE
Include trim option

### ISSUE THREAD

**Issue by benjaminleonard** [oramasearch/highlight#2]
Would be useful to have the option to trim to a string length either side of the match/matches. Currently doing this outside of the plugin, but requires two function calls – the first to get the positions and the second to highlight the text after it's been trimmed. You can't do it before in case you end up wiping out one of the `mark` tags.

Not sure the best way to select which position to choose to trim and return. Happy to submit a PR if you'd find it helpful.

**Comment by micheleriva** [comment]
Nice idea, thanks! Would you mind sharing just a couple of test cases for me to work on?

**Comment by benjaminleonard** [comment]
Great! Here's a basic example I am using here:

```tsx
const highlightedContent = useMemo(() => {
  let content = hit.document.content as string
  const { positions } = highlight(content, searchTerm)

  const firstMatch: number =
    positions.length > 0 && positions[0].start ? positions[0].start : 0

  const start = Math.max(firstMatch - trim / 2, 0) 
  const end = Math.min(start + trim, content.length)

  if (content.length > trim) {
    content = `${start === 0 ? '' : '...'}${content.slice(start, end)}...`
  }

  return highlight(content, searchTerm).toString()
}, [hit, searchTerm, trim])
```

<img width="811" alt="image" src="https://github.com/oramasearch/highlight/assets/4020798/cf155388-a284-4f40-9678-c136b047eac7">

Here's one where the trimmed string length is greater than `trim` –

<img width="759" alt="image" src="https://github.com/oramasearch/highlight/assets/4020798/d1d0773d-ad5f-481e-93d8-6dbf51598cef">

Each item is a single text section (basically the text until the next heading tag) so can be thousands of characters long). Hope that helps!

**Comment by micheleriva** [comment]
Hi @benjaminleonard,
I've started a first step to support this functionality. Beware, it introduces a breaking change (the APIs changed and the function has become a class):

```js
import { Highlight } from '@orama/highlight'

const inputString = 'The quick brown fox jumps over the lazy dog'
const toHighlight = 'brown fox jump'

const highlighter = new Highlight()
const highlighted = highlighter.highlight(inputString, toHighlight)

console.log(highlighted.positions)
// [
//    {
//      start: 10,
//      end: 14
//    }, {
//      start: 16,
//      end: 18
//    }, {
//      start: 20,
//      end: 23
//    }
//  ]

console.log(highlighted.HTML)
// "The quick <mark class="orama-highlight">brown</mark> <mark class="orama-highlight">fox</mark> <mark class="orama-highlight">jump</mark>s over the lazy dog"

console.log(highlighted.trim(10))
// "...uick <mark class="orama-highlight">brown</mark>..."
```

I haven't been able to avoid two function calls yet... I'll work on that as soon as possible.

**Comment by benjaminleonard** [comment]
Thanks, this looks great, I'll give it a try!

FWIW the two function calls are not a problem, it was mostly because the highlight logic was running twice.

That said an alternate approach might be an options param: `{trim: 10}` and have HTML be trimmed automatically.

**Comment by micheleriva** [comment]
yeah not a bad idea either... need to work on that :)
